---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint2
  labels:
    app: endpoint2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: endpoint2
  template:
    metadata:
      labels:
        app: endpoint2
    spec:
      containers:
      - name: endpoint2
        image: gcr.io/<PROJECT>/endpoint2:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: endpoint2
  labels:
    run: endpoint2
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: endpoint2
