---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint1
  labels:
    app: endpoint1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: endpoint1
  template:
    metadata:
      labels:
        app: endpoint1
    spec:
      containers:
      - name: endpoint1
        image: gcr.io/<PROJECT>/endpoint1:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: endpoint1
  labels:
    run: endpoint1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: endpoint1
